name: vicly-basic-pipeline

on:
  push:
    branches: [ master, develop ]

  pull_request:
    branches: [ master, develop ]

jobs:
  checkfmt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Cache SBT ivy cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v5

      - name: Format check
        run: sbt fmtCheck

  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.11, 2.13.1]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Cache SBT ivy cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v5

      - name: Run tests & coverage
        run: sbt ++${{matrix.scala}} clean coverage +test coverageReport

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
